# Generated by Django 4.1.3 on 2023-01-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
