# Generated by Django 4.1.3 on 2022-12-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-public_day',)},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='insert_date',
            new_name='public_day',
        ),
        migrations.RemoveField(
            model_name='product',
            name='update_date',
        ),
    ]
